OSHS2019/platform

client/Data/index.js
collections/index.js
server/EDFBackend.js

Crowdeeg 5

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js

fixed some more stuff 
2 pieces of comments regarding the pr
[8:50](https://sleepandbrainhealth.slack.com/archives/D03VC3J5RUN/p1663030207352189)
the y-limits work great, but they don't persist when you flip the page, please make sure they do
[8:50](https://sleepandbrainhealth.slack.com/archives/D03VC3J5RUN/p1663030239968179)
2. There's too many console logs, it slows down the program, make sure you comment them out after debugging

Crowdeeg 7 ylimit toggle on off displaying data outside of range manually indicate upper and lower bounds

---

client/Annotators/EDF/timeSeriesAnnotator.js

Revert "display durations"

---

client/Annotators/EDF/timeSeriesAnnotator.js

Revert "Revert "fixed download and change timescale""

---

client/Annotators/EDF/timeSeriesAnnotator.js

Revert "Revert "display durations""

---

client/Annotators/EDF/timeSeriesAnnotator.js

Fixed display duration bug

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js

need to reload page after every single action related to annotations

working but could use a lot of improvement

---

client/Annotators/EDF/timeSeriesAnnotator.js

Created functions for shifting yData for alignment, and the auto-limiter.

CROWDEEG-61 Modulate alignment and auto-limiter

---

server/adminCreation.js
server/dataInitialization/basicDemo.js

Created onCreateUser method so that the first user created is the admin. 
To test:
- Wipe DB and reset: meteor reset
- ./up

CROWDEEG-73 Make first user the admin

---

client/Data/index.js
server/EDFBackend.js

Problem only included files with special characters or spaces in their names. Given that the _id property in Mongo only contains word characters, any file whose name contained a space or a bracket was not removed.

CROWDEEG-77 Fix delete functionality in the Data tab

---

client/Data/index.html
client/Data/index.js

Added back commented code in html file as well as adding limit:limit to the settings() function

REVERT-CROWDEEG-75 Add back commented code

---

client/Data/index.js
server/EDFBackend.js

The first time a duplicate file is detected during upload, the user is prompted on whether to overwrite or skip duplicate files. If allowed, duplicate files are deleted before upload. Additionally, backend file deletion code now deletes both the EDFFile entry and the Data entry simultaneously, relying on the path being related to the EDFFile ID.

CROWDEEG-90 Allow Duplicate Files to be Overwritten

---

client/Annotators/EDF/timeSeriesAnnotator.js

Channels that did not have many (or any) oscillations and remained flat had a scaling factor or -Infinity or Infinity. Normally, when the data points were 0 this wasn't an issue, but when the points became values such as -0.0001, these values would get blown up to Infinity and thus go missing. In this event, keep the scaling factor at 1. 
Now when trying to mask and restore, it is identical to the values above it, which is wrong -> Different Jira Task

CROWDEEG-83 Fix missing channels

---

client/Annotators/EDF/timeSeriesAnnotator.js

The graph points (which control the tooltip path) and ruler now properly update when reversing polarity. The ruler now redraws on chart redraw.

CROWDEEG-102 Fix Reverse Polarity Issues

---

client/Annotators/EDF/timeSeriesAnnotator.js

Separates the jQuery events from _populateGraph to improve efficiency.

CROWDEEG-103-Separate-jQuery-Events-From-populateGraph

---

client/Annotators/EDF/timeSeriesAnnotator.js

The channel spacing is maintained and any channels above the masked channel are simply 'shifted down'. _getChannelIndexFromYValue() still returns the index of the channel in the original array, not the array filtered by the masking, and the data array remains unchanged, the relevant channels are simply hidden.
This branch depends on CROWDEEG-103 (https://github.com/OSHS2019/platform/pull/75)

CROWDEEG-88 Hide masked channels and redistribute remaining ones

---

client/Annotators/EDF/timeSeriesAnnotator.js

Added reverse polarity to saved preferences.
Fixed y-axis limit saving.

CROWDEEG-101-Add-And-Fix-Preferences

---

client/Data/index.js
server/EDFBackend.js

Make the delete button in the data tab to also delete from the Assignments collection so that we don not have "loading.." assignments in the home page.

CROWDEEG-104 Make delete remove from Assignments

---

client/Annotators/EDF/timeSeriesAnnotator.js

Added done button, which just sets the Assignment to 'Completed' and returns the user to the home page.

CROWDEEG-91 Add done button

---

client/Data/index.js
collections/index.js
server/dataInitialization/basicDemo.js

Added a defaultTask field to Data collection which saves the corresponding task on file upload. If a task already exists with that file, we assign the defaultTask to said task. Then when selected we search for the defaultTask of that Data collection. If no defaultTask we check if there is an "edf template...." of the file and assign that task to it.
Also added defaultTask to the initial PSG and ANNE files for the test user, so when selecting one of those, the task always automatically appears when assigning.

CROWDEEG-92 Save Task Object Complete

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js

Most UI items have been moved to dropdown menus located above the graph. UI menu items are either implemented as links which do something when clicked, hoverable expandable menus, or links which open dialogs. Most functionality is implemented using Materialize.
In addition to the materialize dropdown classes, I have added 'dropdown-menu' (for dropdowns with unconstrained width), 'dropdown-submenu' (for hoverable 'select' style dropdowns). To add a 'select' style dropdown, make a link (a) element with the dropdown-submenu class and a data-activates attribute which targets a ul. The ul then must contain list elements with links inside. Once that structure is followed, a checkmark should be added to each element on click.

CROWDEEG-98 Update UI With Dropdowns

---

client/Annotators/EDF/timeSeriesAnnotator.js

Fix annotation labels when masking, however when you mask a lot of channels, when creating a box, you need to create the box horizontally to auto-render to the previous label. (by horizontally I mean make the box but then just move your mouse to the right/left not up or down)

CROWDEEG-106 Fix annotation labels when masking

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js

Added a new dialog under Annotations > Annotation Manager. This dialog contains a table of annotation data, which can be clicked on to jump to annotations, and allows for filtering, sorting, and bulk deletion.
_populateAnnotationManagerTable() fully refreshes the table with the given annotations, while _filterAnnotationManagerTable() filters on the pre-existing table elements (_populateAnnotationManagerTable() internally calls _filterAnnotationManagerTable()). _populateAnnotationManagerTable() takes an optional sorting function to facilitate ordering of the table elements. This function is cached, so if it is omitted or undefined the table will use the last used sorting function, or sort by time as a default if no cached function exists.

CROWDEEG-81 New Annotation Manager

---

client/Annotators/EDF/index.js
client/Annotators/EDF/timeSeriesAnnotator.js
client/Data/index.html
client/Data/index.js
collections/index.js
server/DataTable.js
server/EDFBackend.js

We no longer explicitly set the fileID on upload, so the file library automatically generates one instead. Some incidental changes to how the file name is passed into the annotator and how files are deleted also had to be made. Additionally, included a few bugfixes related to deleting files.

CROWDEEG-109 Replace EDFFile file ids with randomly generated ids

---

client/Annotators/EDF/index.js
client/Annotators/EDF/timeSeriesAnnotator.js
client/Assignment/index.html
client/Assignment/index.js
client/Data/index.js
collections/index.js
server/EDFBackend.js
server/methods.js

Review system for admin->assignee relationship. This will only work for new assignments, current assignments will should be just marked as "done"
On assignee side:
- Once they click "done" a new assignment will appear for the reviewer with all the annotations, and their assignment will be in the review column.
- A feedback button which sends a window alert with the feedback from the reviewer (default is "No feedback")
On reviewer side:
- Assignments should appear in the Review column, with the assignee's username attached to the file so you know who's assignment you are working on.
- The "Send Changes" button sends the reviewers changes back to the assignee.
- The "Reject" button allows the reviewer to input some feedback and send the assignment back to the assignee (makes the assignee's …

CROWDEEG-95 Review System

---

client/Data/index.js
server/DataTable.js

Adds table count beside the "Showing x of y" on the bottom of the table. However I cannot get them on separate lines.

CROWDEEG-111 Add Table Count

---

client/Annotators/EDF/timeSeriesAnnotator.js

The windows cache can hold up to 15 entries, with the entries farthest away from the new entry being dropped.

CROWDEEG-107 Reenable Window Caching

---

client/Annotators/EDF/timeSeriesAnnotator.js

Move the done button up to the top of the page.

CROWDEEG-119 Move done to top of screen

---

client/Annotators/EDF/timeSeriesAnnotator.js
collections/index.js
server/EDFBackend.js

- Fixed review system (problem is that we check if the user has a role so we dont put the test account's files in review, but Rosa had a global role, but it was null so it assumed that the account was either admin or tester) -> cant really test this as I an not sure how the account had __global_roles__ defined as null
- Add preferences to the review assignment and when you send changes back to the assignee.
- Fixed bug with alignment where the files were opposite (occasionally it was file2 + file1 instead of file1 + file2)

CROWDEEG-123 Fix review, add preferences, fix bugs

---

client/Annotators/EDF/timeSeriesAnnotator.js

Clicking the "title" button at the top right of the screen will hide the title and the "latest change point previous page" box/label. Pressing the button again will show it.

CROWDEEG-117 Toggle Title and Change Point Label

---

client/Annotators/EDF/timeSeriesAnnotator.js

Created an event to keep track of the last clicked point of the graph, then when zooming in only (selecting a smaller timescale), the graph will centre on said point.

CROWDEEG-115 Centre on last point clicked on zoom

---

client/Annotators/EDF/timeSeriesAnnotator.js

Replaced comment column with duration.

CROWDEEG-122 Add Duration to Annotation Manager

---

client/Annotators/EDF/timeSeriesAnnotator.js
client/Data/index.html
client/Data/index.js
client/Data/style.css

Added a spinner to the data tab and annotator. Also moved the 'Toggle Table' button to the Display dropdown to make room for the spinner in the annotator page. If we need to add more instances of the loading then:
In the data tab:
- Just set the reactive variable loading to true (to show) or false (to hide) ie loading.set(true)
In the annotator:
- Just call function _showLoading() or _hideLoading()

CROWDEEG-116 Add loading spinner to data tab and annotator

---

client/Annotators/EDF/index.js
client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js

Due to the similarities between aligning by timestamp and by crosshair, I merged the two - clicking on the graph to set a crosshair will update the timestamp in the inputs, while updating the inputs will also place crosshairs on the graph, so the methods are interchangeable.

CROWDEEG-118 Align By Time Stamp

---

client/Annotators/EDF/timeSeriesAnnotator.js

Includes alignment in CSV file. Uploading CSV also changes the alignment (used same logic as the JSON file).

CROWDEEG-120 Included alignment in CSV

---

client/Annotators/EDF/timeSeriesAnnotator.js

Function and Cache definitions have been altered. _getNonTrivialUniversalAnnotations() now filters a given list instead of using chart.annotations.allItems, and is only used so far to help update the universalChangePointAnnotationsCache, which now contains all non trivial change point annotations instead of just the visible ones. 
Importantly, universalChangePointAnnotationsCache now contains Annotation data objects instead of annotation drawings on the graph, so annotation.options.xValue is replaced with annotation.position.start.

CROWDEEG-128 Fix Previous Change Points

---

client/Annotators/EDF/timeSeriesAnnotator.js
client/Assign/index.html
client/Assign/index.js
client/Data/index.html
client/Data/index.js
client/Preferences/index.html
client/Preferences/index.js
client/Preferences/style.css
client/index.html
collections/index.js
router/index.js
server/DataTable.js
server/EDFBackend.js
server/pubs.js

In this PR users should be able to:
Admin:
- Upload and delete preferences files in the Preferences tab
- Assign Preferences files when assigning tasks in the Data tab (preferences should be optional)
- Assign Preferences files when assigning tasks in the Assign tab (preferences should be optional)
All Users:
- View the Preferences directory when annotating (Go to Metadata -> Preferences -> View Preferences Directory) where users can click a file and the preferences will get uploaded to the annotator (Basically the same as the Annotation Manger).
(Also added the loading spinner when changing timescales)

CROWDEEG-126 Preferences Files Directory

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js
server/EDFBackend.js

Added the ability to import Annotations from other assignments with the same tasks (or files if the user is an admin). Currently, this is done by copying all relevant annotations from the database with some adjustments to change ownership.

CROWDEEG-127 Import Annotations

---

client/Preferences/index.html
client/Preferences/index.js

Allows users to download the selected preferences in the preferences tab.

CROWDEEG-132 Download Preferences from the Preferences Tab

---

client/Annotators/EDF/timeSeriesAnnotator.js

Shows the max and min of a channel when you go to 'Channel' -> 'Show Max/Min'
To hide the max and min lines, go to 'Channel' -> 'Hide Max/Min'

CROWDEEG-133 Show max and min of a channel

---

client/Annotators/EDF/timeSeriesAnnotator.js

Refactored the JSON files for alignment into {filename1:"", filename2:"", lag:""}. Also fixed bugs in the _parseFile and downloadJSON functions.

CROWDEEG-134 Refactored JSON and fixed bugs

---

client/Annotators/EDF/timeSeriesAnnotator.js
client/Data/index.html
client/Data/index.js
server/DataTable.js
server/EDFBackend.js

Assignments can either be deleted within the annotation manager, or by an admin on the data tab.

CROWDEEG-138 Allow Deleting Assignments

---

client/Data/index.html
client/Data/index.js

Allow users to bulk assign alignments with a CSV file. Example CSV file attached
[test.csv](https://github.com/OSHS2019/platform/files/11042717/test.csv)

CROWDEEG-136-Bulk-Assignment

---

client/Annotators/EDF/timeSeriesAnnotator.js

Fixed annotation upload when uploading csv file to the annotator. I couldnt exactly replicate Rosa's issue (could have been fixed in previous PR), however I ran into some other issues (label not showing) which are fixed in this PR.
Also fixes issues with certain csv files not working. Sometimes when we read from the csv file, every string has quotes generated around them, so the only solution is to replace the quotes as the function cannot work with quotes around everything

CROWDEEG-139 Fixed Uploading Annotations

---

client/Alignments/index.html
client/Alignments/index.js
client/Alignments/style.css
client/Annotations/index.html
client/Annotations/index.js
client/Annotations/style.css
client/Annotators/EDF/timeSeriesAnnotator.js
client/Data/index.js
client/index.html
collections/index.js
router/index.js
server/DataTable.js
server/methods.js
server/pubs.js

This PR created:
- Alignment tab to upload alignment JSONs
- Annotations tab to upload annotation CSVs
- Allow users to include the alignment file OR just a number in the CSV file 
- Allow users to include the annotation file (works mainly for box annotations -> if problem we can make a ticket for the future)
- Reconfigured alignment JSONs so that they now show negative numbers (if the lag is negative, the bottom channel moves, if lag is positive then the top channel moves)

CROWDEEG-140-Improved-Bulk-Assignment-With-Alignment

---

client/Annotators/EDF/timeSeriesAnnotator.js
server/EDFBackend.js

The important change in this PR is that the data's sampling_rate is now represented as an object with a different sampling rate per file, mostly useful in alignment tasks.

CROWDEEG-147 Fix Alignment Issues

---

client/Annotators/EDF/timeSeriesAnnotator.js

Created the adjustable fast forward feature. To use it, go to Display -> Adjust Fast Forward

CROWDEEG-144 Adjustable Fast forward

---

client/Data/index.js

Remove task requirement from the user and adapt to python csv which has the first columns all numbers. Also fixed one bug. Attached is an example of the python csv format
[batch_alignment_Axivity.csv](https://github.com/OSHS2019/platform/files/11113995/batch_alignment_Axivity.csv)

CROWDEEG-148  Remove task requirement and adapt to python-csv

---

client/Annotators/EDF/timeSeriesAnnotator.js
client/Data/index.html
client/Data/index.js

Gives users the option to just put one file in the csv file for batch assignment (file name must be in File1 column, File2 remains empty)
Also added a loading spinner when uploading annotations

CROWDEEG-149 Allow Single file for Batch Assignment

---

client/Annotators/EDF/timeSeriesAnnotator.js

Also contains a small bugfix where one option was attempting to filter for 'Automatic Arousal' instead of 'Autonomic Arousal'.

CROWDEEG-113 Retain Annotation Filter When Switching Pages

---

client/Data/index.js

Fixed bug where the loading spinner would never disappear when you click the Batch Assignment or Upload Chosen Files button

CROWDEEG-150 Remove loading when no files uploaded in Data tab

---

client/Assign/index.html
client/Assign/index.js

Added annotations to the quick assign. (Now you can select an annotations file like Preferences). Note that alignment is not implemented for quick assign so I cannot add an option for alignment files. However this PR prepares for the alignment files and just has some of the code for them commented out.

CROWDEEG-151 Add Annotations to quick assign

---

client/Data/index.js

Better and more descriptive error messages for batch assignment with CSV file.

CROWDEEG-151 Better Error Msgs for Batch Assignment

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js
client/Data/index.js

Also adds some more descriptive messaging to annotation imports, and slightly reworks the annotation import table. Duplicate annotations are also no longer ignored.

CROWDEEG-152 Add Dialog to import Annotations directly from the Directory

---

client/Data/index.js

Added a check for the task for file2 if the task for file1 cannot be found. Also added some comments for the new co-op students next week

CROWDEEG-155 Add Extra Check for Task in Batch Assignment + Comments

---

router/index.js
server/pubs.js

Note there are no security checks, every annotation file in the directory is currently published, as I don't think there's a reason to restrict it.

CROWDEEG-156 Publish Annotation Directory to All Users

---

client/Annotations/index.js

Added notifications to when a user uploads annotations.

CROWDEEG-165 Annotation Notifications

---

client/Annotators/EDF/style.css
client/Annotators/EDF/timeSeriesAnnotator.js
server/EDFBackend.js
server/pubs.js

Users also have the ability to change the colour map of annotations to users through the annotation manager.

CROWDEEG-157 Annotations Track Their Last Editor

---

client/Annotators/EDF/timeSeriesAnnotator.js
client/Assignment/index.js

completed assignments will not be sent to review when pressing 'done'; instead, a dedicated button will do this while
completed assignments will still be in the done column.

Added send back to review button

---

client/Assignment/index.js

one-liner to add a condition to prevent the removal of an assignment from the client side

added condition to delete assignment call

---

server/pubs.js

slightly changing fetch request logic to see if performance improves

removed revisions from meteor.users find
