client/Annotators/EDF/timeSeriesAnnotator.js

If an error occurs during tooltip rendering, the JS error message is now displayed to the user. I was unable to cause an error during normal workflow, so it was tested by intentionally throwing an error in the try body.

CROWDEEG-66 Change Error Message of Graph Tooltip to be More Descriptive

---

client/Annotators/EDF/timeSeriesAnnotator.js

The timeScaleSetting options carry over between assignments, so when adding the option, the code now checks if it already exists, and if so updates it accordingly.

CROWDEEG-74 Fix Multiple Full Recording Options

---

client/Annotators/EDF/timeSeriesAnnotator.js

When hovering over the edit or delete buttons, including hovering over the dropdown (where you click edit and choose a problem (apnea, etc.) the tooltip label will not show until you remove the mouse from the buttons.

CROWDEEG-53-Hide-Tooltip

---

client/Data/index.html
client/Data/index.js

Added HTML filters so that Path and Patient # no longer need to be specified using the full string
Before when page refreshes, the table would only render 10 items (the default limit) and you would have had to click "Next Page" for it to re-render. Now it correctly renders all items when going onto the page (could have been Rosa's problem when not being able to see the files she uploaded as she had over the limit 10).

CROWDEEG-75-Fix-Data-Filters

---

client/Data/index.js
collections/index.js
server/EDFBackend.js

The issue with this fix is that the values in the call to helpers.sanitize() are hardcoded to be consistent with those of the ostrio:files library. Changes to that library (specifically if the maximum fileId length is reduced) may be a breaking change. 
As a solution, we could provide our own sanitization function which restricts parameter inputs - what are your thoughts on that?

CROWDEEG-93 Fix File Ids

---

client/Annotators/EDF/timeSeriesAnnotator.js

Channel 'points' in highchart now also properly follow scaled channels. The issue was the yData array was being updated directly, which did not update the graph points along with it (which highcharts automatically does in the setData function).
Currently the 'Mask channel' and 'Limit Y axis' functions set yData directly as well - this hides the lines on the graph, but leaves the associated points, meaning the tooltip can still detect and read them - is this behaviour desirable?

CROWDEEG-80 Tooltip Follows Graph Lines

---

client/Annotators/EDF/timeSeriesAnnotator.js

Alignment and JSON file names are now prepended with the record name(s) (without extension) of the records being annotated.

CROWDEEG-87 Change Downloaded File Names

---

client/Annotators/EDF/timeSeriesAnnotator.js

New box annotations now default to the previous box annotation label. Just make the box then move the cursor away.
However, sometimes when making the box and dragging the box past the bottom of the graph, it fails to render, but this would not be an issue when using the app normally.

CROWDEEG-82-Make-Default-Box-Label-Same-As-Previous

---

client/Annotators/EDF/timeSeriesAnnotator.js

- Preferences are now saved, so when you reload a page the common filters (timescale, channel masking, limiting, amplitude, translation) remain.
- Note: time sync already seems to be included in the saved preferences
- Can also download and upload preferences, however there is no system in place to ensure that you are uploading compatible preferences. For example, if you upload preferences for a chart with 12 channels to a chart with 6 channels, there will be a rendering error.
- Should fix CROWDEEG-94, since the issue with the channels blowing up when changing amplitudes then switching pages has been resolved.
- when downloading the initial preferences (when you first start the task), these preferences should revert everything back to the way it was initially.
- When you save the …

CROWDEEG-85-Save-Preferences

---

client/Annotators/EDF/timeSeriesAnnotator.js

Ruler is implemented as a "drawable" ruler. Starting from a point, the user can then extend the ruler with the mouse and add the 'ticks' and values with further clicks. Middle mouse button disables further drawing and allows the ruler to be freely moved.
The numbers on the ruler may be a little hard to read at times, and I'm not yet sure how practical the 'drawable' nature is for normal workflow, but if need be we should be able to create a fixed ruler size from this code by constructing the 'rulerPoints' array ourselves instead of building it from clicks.

CROWDEEG-86 Add adjustable ruler for graph data.

---

client/Annotators/EDF/timeSeriesAnnotator.js

The annotation labels in the manager now only include the annotationLabel and the start time. The delete and view functionalities are fixed and are faster due to the separation of the jQuery events from the select container updater. 
Note: If a function has jQuery events (ie $().click()....) then those events are running the whole time, so when we recall the function, these events are duplicated, which is most likely the reason for the slower times when shifting pages, since we call the _populateGraph function each time, hence the jQuery events are being duplicated => slow.

CROWDEEG-96-Fix-Annotation-Manager

---

client/Annotators/EDF/timeSeriesAnnotator.js

Now when you choose a very large timescale, the navigator does not produce negative time, or include time outside the max recording length.

CROWDEEG-84 Fix x-axis zeroing issue

---

client/Annotators/EDF/timeSeriesAnnotator.js
server/EDFBackend.js

Given that masking now hides the channel, instead of a selective channel display, we optimise page switching and masking by only updating unmasked channels, to speed up pagination when there are less channels. 
Also includes the separation of masking and unmasking given that the _switchToWindow function is called twice.

CROWDEEG-100 Optimise masking and page switching

---

client/Annotators/EDF/timeSeriesAnnotator.js

Fixes a scrollbar appearing when masking channels. All that was needed was to comment out the enabling of said scrollbar. Scrollbar doesnt seem to affect anything so it should be fine removing it.

CROWDEEG-108 Fix masking repeatedly

---

client/Annotators/EDF/timeSeriesAnnotator.js

To avoid duplicate JQuery dialogs, all dialogs are destroyed upon switching to a new annotator. This comes with the risk of destroying any dialogs created prior to opening the annotator, however it also gives the flexibility to add new dialogs to the annotation manager later without worrying about the duplication issue.
Also fixed an issue with Annotation Manager pagination.

CROWDEEG-110 Avoid Duplicate Dialogs

---

client/Annotators/EDF/timeSeriesAnnotator.js
server/EDFBackend.js

This PR should fix the issue when switching pages and the annotations are slightly off. Problem was that we round the samplingRate in the backend which skews the data each time we call get.edf.data

CROWDEEG-97 Fix display shift issue

---

client/Annotators/EDF/timeSeriesAnnotator.js

The annotations cache is no longer cleared when switching windows, and in some places the keys have been changed to be based on the window position instead of the annotation position. Cache length has also been capped at 15, with replacement based on farthest start time from the added element, similar to the window cache.
Additionally, we no longer save annotations when switching windows, and flushing annotations no longer clears the cache.

CROWDEEG-112 Update Annotations Cache

---

client/Data/index.js
server/DataTable.js

Rename Path column to Name.
Change provided data back to name instead of id while retaining the path format.
Since search is based on the provided data instead of the rendered data, prevent searching on columns which take the id as data to prevent unexpected behaviour.
Note since the search is based on the provided data and not the formatted data, searching based on the path (e.g. /physionet) will not yield results.

CROWDEEG-114 Fix Data Search

---

client/Annotators/EDF/timeSeriesAnnotator.js

Added select all and deselect all buttons to the annotation manager, which allow for the deleting of all annotations. Both of these buttons respect the current filter.

CROWDEEG-121 Add Ability to Delete All to Annotation Manager

---

client/Annotators/EDF/timeSeriesAnnotator.js

Caches are now properly cleared when aligning the graph (and performing any function that uses _reloadCurrentWindow()

CROWDEEG-124 Fix Alignment not Properly Reloading Window

---

client/Annotators/EDF/index.js
client/Annotators/EDF/timeSeriesAnnotator.js

Downloaded files were using the file ids instead of their original names. I believe this broke when the switch was made to let EDFFile generate IDs.

CROWDEEG-125 Fix Metadata File names

---

client/Annotators/EDF/timeSeriesAnnotator.js

Turns the annotations off temporarily when using the ruler or time-sync by cross-hair. Once completed, the annotation will go back to its previous state.

CROWDEEG-130 Turn Annotation Off Temporarily When Needing Click

---

server/addAdminRole.js

Allows for the admin to assign other users as admin in the Manage section. All that was needed was to add the "admin" as a possible role done in the backend.

CROWDEEG-131 Allow Admins to Create Other Admins

---

client/Annotators/EDF/timeSeriesAnnotator.js

Moved the scaling and translation buttons onto the main screen (they are still in the channel menu as well)

CROWDEEG-145 Moved Common Buttons From Channel Menu

---

client/Annotators/EDF/timeSeriesAnnotator.js

When uploading preferences via file / preference directory during annotation, the start time is checked to make sure it is not negative and that it does not exceed the recording time; otherwise, the file is rejected. These are the only two places where location.reload() is called.

CROWDEEG-164 Valid Start Time Checked for Preferences

---

client/Annotators/EDF/timeSeriesAnnotator.js

When a file is put 'In Review' the reviewer should start at the beginning of the file. Fixed by setting startTime to 0 before we upload preferences

CrowdeEEG-168: Reviewer starts at beginning

---

collections/index.js

Added a cap to the number of revisions stored in each account. These revisions essentially just stored the roles a user has and their "last" login date. Some accounts have accumulated up to 6000+ revisions, which is too much for the database to handle when logging on.

changed account revision cap to 250
